# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='blogs',
        ),
        migrations.RemoveField(
            model_name='like',
            name='posts',
        ),
        migrations.AddField(
            model_name='blog',
            name='pic',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
