# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170328_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
