# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170328_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pic'),
        ),
    ]
